DROP TABLE TRATAMIENTOS IF EXISTS;
CREATE TABLE TRATAMIENTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO INT NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
PRECIO DECIMAL(5,2) NOT NULL);

INSERT INTO TRATAMIENTOS VALUES (DEFAULT, 32456, 'CONSULTA GENERAL', 120),
(DEFAULT, 09876, 'CONSULTA ESPECIALIZADA', 500)